name: NPM test
on: [push, pull_request]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Build project
        run: |
          npm ci
          npm run build
      - name: Test project
        run: npm run test
      - name: Upload gh-pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/
  deploy-to-gh-pages:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: success() && github.ref == 'refs/heads/main'
    # Required permissions for upload-pages-artifact.
    permissions:
      pages: write
      id-token: write
    # Deploy to the github-pages environment.
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: .
      - name: Publish
        uses: actions/deploy-pages@v4
        with:
          path: .
