name: NPM test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Build project
        run: |
          npm ci
          npm run build
      - name: Test project
        run: npm run test
